import { useCallback,useEffect,useMemo,useRef,useState } from 'react'
import { Activity,Filter,X } from 'lucide-react'
import type { ApiClient,EventRecord,ExecutionDetail,ExecutionStatus,HistoryItem,HistoryQuery } from '../api/types'
import type { StreamStatus } from '../hooks/useEventStream'
import { PageHeader } from '../components/PageHeader'
import { EmptyState } from '../components/EmptyState'
import { InlineError,LoadingSkeleton } from '../components/Feedback'
import { StatusBadge } from '../components/StatusBadge'

const active=new Set<ExecutionStatus>(['QUEUED','CONNECTING','PARSING','EXECUTING','COMMITTING','LOGGING'])
const safe=(value:unknown)=>typeof value==='string'?value:'—'
export function ActivityPage({api,events,streamStatus}:{api:ApiClient;events:EventRecord[];streamStatus:StreamStatus}){
 const [page,setPage]=useState<{items:HistoryItem[];hasMore:boolean}|null>(null),[error,setError]=useState(''),[draft,setDraft]=useState<Record<string,string>>({}),[filters,setFilters]=useState<HistoryQuery>({}),[offset,setOffset]=useState(0)
 const [detail,setDetail]=useState<ExecutionDetail|null>(null),[detailError,setDetailError]=useState(''),[cancelPending,setCancelPending]=useState<string|null>(null);const request=useRef<AbortController|null>(null),detailRequest=useRef<AbortController|null>(null),cancelRequest=useRef<AbortController|null>(null),terminalRefresh=useRef<ReturnType<typeof setTimeout>|null>(null)
 const load=useCallback(async(next:number,append:boolean)=>{request.current?.abort();const controller=new AbortController();request.current=controller;setError('');try{const value=await api.history({...filters,offset:next,limit:50},controller.signal);if(controller.signal.aborted)return;setPage(old=>({items:append?[...(old?.items??[]),...value.items.filter(item=>!old?.items.some(oldItem=>oldItem.executionId===item.executionId))]:value.items,hasMore:value.hasMore}));setOffset(next)}catch(e){if(!controller.signal.aborted)setError((e as Error).message||'无法读取执行历史。')}},[api,filters])
 useEffect(()=>{void load(0,false);return()=>request.current?.abort()},[filters])
 useEffect(()=>()=>{request.current?.abort();detailRequest.current?.abort();cancelRequest.current?.abort();if(terminalRefresh.current)clearTimeout(terminalRefresh.current)},[])
 const terminalEventKey=events.filter(event=>['completed','failed','cancelled','rejected'].includes(event.status)).at(-1)?.id
 useEffect(()=>{if(!terminalEventKey)return;if(terminalRefresh.current)clearTimeout(terminalRefresh.current);terminalRefresh.current=setTimeout(()=>void load(0,false),150);return()=>{if(terminalRefresh.current)clearTimeout(terminalRefresh.current)}},[terminalEventKey,load])
 const running=useMemo(()=>{const latest=new Map(events.map(e=>[e.executionId,e]));const seen=new Set<string>();const rows:Array<{item?:HistoryItem;event?:EventRecord}>=[];for(const item of page?.items??[]){seen.add(item.executionId);const event=latest.get(item.executionId);const status=(event?.status.toUpperCase()??item.status) as ExecutionStatus;if(active.has(status))rows.push({item:{...item,status}})}for(const event of latest.values()){if(!seen.has(event.executionId)&&active.has(event.status.toUpperCase() as ExecutionStatus))rows.push({event})}return rows},[events,page])
 const apply=()=>{const query:HistoryQuery={};for(const key of ['source','purpose','status','kind','correlationId','startedAfter','startedBefore'] as const)if(draft[key])Object.assign(query,{[key]:draft[key]});for(const key of ['recorded','success'] as const)if(draft[key])Object.assign(query,{[key]:draft[key]==='true'});setOffset(0);setFilters(query)}
 const openDetail=async(id:string)=>{detailRequest.current?.abort();const controller=new AbortController();detailRequest.current=controller;setDetail(null);setDetailError('');try{const value=await api.getExecution(id,controller.signal);if(!controller.signal.aborted)setDetail(value)}catch(e){if(!controller.signal.aborted)setDetailError((e as Error).message||'详情暂时不可用。')}}
 const cancel=async(id:string)=>{cancelRequest.current?.abort();const controller=new AbortController();cancelRequest.current=controller;setCancelPending(id);let accepted=false;try{await api.cancelExecution(id,controller.signal);accepted=true}catch(e){if(!controller.signal.aborted)setError((e as Error).message||'取消请求失败。')}finally{if(!controller.signal.aborted){setCancelPending(null);if(accepted)void load(0,false)}}}
 return <><PageHeader eyebrow="EXECUTION TELEMETRY" title="实时执行" description="共享会话事件流与权威执行历史，SQL 仅显示脱敏摘要。"/>
 {streamStatus!=='connected'&&<div className="activity-warning" role="status">实时通道已过期，正在使用权威历史校对。</div>}
 <section className="ops-section"><div className="section-heading"><span>ACTIVE JOBS</span><StatusBadge tone={running.length?'warning':'success'}>{running.length?`${running.length} 个运行中`:'无运行任务'}</StatusBadge></div>{running.length?<div className="activity-list">{running.map(row=>row.item?<ExecutionRow key={row.item.executionId} item={row.item} onDetail={openDetail} onCancel={cancel} pending={cancelPending===row.item.executionId}/>:<LiveEventRow key={row.event!.executionId} event={row.event!}/>)}</div>:<EmptyState title="当前没有运行任务" description="新的 MCP 或控制台执行会在此出现。"/>}</section>
 <section className="ops-section"><div className="section-heading"><span>HISTORY FILTER</span><Filter size={16}/></div><div className="filter-grid">
  <label>来源<select value={draft.source??''} onChange={e=>setDraft({...draft,source:e.target.value})}><option value="">全部</option><option>CONSOLE</option><option>MCP</option></select></label>
  <label>状态<select value={draft.status??''} onChange={e=>setDraft({...draft,status:e.target.value})}><option value="">全部</option>{['QUEUED','CONNECTING','PARSING','EXECUTING','COMMITTING','LOGGING','COMPLETED','FAILED','CANCELLED','REJECTED'].map(v=><option key={v}>{v}</option>)}</select></label>
  <label>类型<select value={draft.kind??''} onChange={e=>setDraft({...draft,kind:e.target.value})}><option value="">全部</option><option>DDL</option><option>DML</option><option>QUERY</option></select></label>
  <label>用途<select value={draft.purpose??''} onChange={e=>setDraft({...draft,purpose:e.target.value})}><option value="">全部</option>{['PRODUCTION_CHANGE','MIGRATION','TEST','MOCK','SEED','SAMPLE'].map(v=><option key={v}>{v}</option>)}</select></label>
  <label>记录状态<select value={draft.recorded??''} onChange={e=>setDraft({...draft,recorded:e.target.value})}><option value="">全部</option><option value="true">已记录</option><option value="false">未记录</option></select></label>
  <label>结果<select value={draft.success??''} onChange={e=>setDraft({...draft,success:e.target.value})}><option value="">全部</option><option value="true">成功</option><option value="false">非成功</option></select></label>
  <label>关联 ID<input value={draft.correlationId??''} onChange={e=>setDraft({...draft,correlationId:e.target.value})}/></label><label>开始日期起<input type="datetime-local" onChange={e=>setDraft({...draft,startedAfter:e.target.value?new Date(e.target.value).toISOString():''})}/></label><label>开始日期止<input type="datetime-local" onChange={e=>setDraft({...draft,startedBefore:e.target.value?new Date(e.target.value).toISOString():''})}/></label>
 </div><div className="filter-actions"><button className="button-secondary" onClick={()=>{setDraft({});setFilters({});setOffset(0)}}>重置</button><button className="button-primary" onClick={apply}>应用筛选</button></div></section>
 {error?<InlineError message={error} onRetry={()=>void load(0,false)}/>:!page?<LoadingSkeleton label="正在读取执行历史"/>:page.items.length?<section className="ops-section"><div className="activity-list">{page.items.map(item=><ExecutionRow key={item.executionId} item={item} onDetail={openDetail} onCancel={cancel} pending={cancelPending===item.executionId}/>)}</div>{page.hasMore&&<button className="button-secondary load-more" onClick={()=>void load(offset+50,true)}>加载更多</button>}</section>:<EmptyState title="没有匹配的执行历史" description="调整筛选条件后重试。"/>}
 {(detail||detailError)&&<div className="drawer-backdrop"><aside className="detail-drawer" role="dialog" aria-modal="true" aria-label="执行详情"><button className="icon-button drawer-close" aria-label="关闭执行详情" onClick={()=>{setDetail(null);setDetailError('')}}><X/></button><h2>执行详情</h2>{detailError?<InlineError message={detailError}/>:detail&&<><pre className="safe-summary">{safe(detail.summary.sqlSummary)}</pre><dl className="detail-facts"><div><dt>阶段</dt><dd>{safe(detail.summary.phase)}</dd></div><div><dt>状态</dt><dd>{safe(detail.summary.status)}</dd></div></dl><h3>语句事实</h3>{detail.statements.map((s,i)=><p key={i}><code>#{String(s.index??i)}</code> {safe(s.kind)} · {safe(s.status)} · {safe(s.sqlSummary)}</p>)}<h3>阶段事件</h3><ol>{detail.events.map(e=><li key={e.sequence}><code>{e.sequence}</code> {e.status} · {e.detail}</li>)}</ol></>}</aside></div>}</>
}
function ExecutionRow({item,onDetail,onCancel,pending}:{item:HistoryItem;onDetail(id:string):void;onCancel(id:string):void;pending:boolean}){return <article className="execution-row"><div className="execution-glyph"><Activity size={17}/></div><div><div className="execution-meta"><StatusBadge tone={item.status==='COMPLETED'?'success':item.status==='FAILED'?'danger':'warning'}>{item.status}</StatusBadge><code>{item.executionId.slice(0,8)}</code><span>{item.source}</span><span>{item.purpose??'读取'}</span></div><strong>{item.sqlSummary||'无可用 SQL 摘要'}</strong><small>{new Date(item.startedAt).toLocaleString('zh-CN')} · 影响 {item.affectedRows} / 返回 {item.returnedRows} · DB {item.connectionFingerprint.slice(0,12)}</small></div><div className="row-actions"><button className="button-secondary" aria-label="查看执行详情" onClick={()=>onDetail(item.executionId)}>详情</button>{active.has(item.status)&&<button className="button-danger" aria-label="取消任务" disabled={pending} onClick={()=>onCancel(item.executionId)}>{pending?'取消请求中':'取消'}</button>}</div></article>}
function LiveEventRow({event}:{event:EventRecord}){return <article className="execution-row"><div className="execution-glyph"><Activity size={17}/></div><div><div className="execution-meta"><StatusBadge tone="warning">{event.status.toUpperCase()}</StatusBadge><code>{event.executionId.slice(0,8)}</code><span>LIVE EVENT</span></div><strong>正在同步脱敏 SQL 摘要</strong><small>{new Date(event.timestamp).toLocaleString('zh-CN')} · {event.detail||'阶段已更新'}</small></div></article>}
