import { useCallback,useEffect,useRef,useState } from 'react'
import { Clipboard,Download,FileClock,RotateCcw,ShieldAlert } from 'lucide-react'
import type { ApiClient,ReleaseArtifact,ReleaseSnapshot } from '../api/types'
import { PageHeader } from '../components/PageHeader'
import { InlineError,LoadingSkeleton } from '../components/Feedback'
import { EmptyState } from '../components/EmptyState'
import { StatusBadge } from '../components/StatusBadge'
import { ConfirmDialog } from '../components/ConfirmDialog'

export function ReleasePage({api}:{api:ApiClient}){const [snapshot,setSnapshot]=useState<ReleaseSnapshot|null>(null),[error,setError]=useState(''),[exportOpen,setExportOpen]=useState(false),[ack,setAck]=useState(false),[busy,setBusy]=useState(false),[recover,setRecover]=useState<ReleaseArtifact|null>(null);const request=useRef<AbortController|null>(null)
 const load=useCallback(async()=>{request.current?.abort();const c=new AbortController();request.current=c;setError('');try{const value=await api.release(c.signal);if(!c.signal.aborted)setSnapshot(value)}catch(e){if(!c.signal.aborted)setError((e as Error).message||'无法读取发版日志。')}},[api]);useEffect(()=>{void load();return()=>request.current?.abort()},[load])
 const doExport=async()=>{setBusy(true);setError('');const c=new AbortController();try{await api.releaseExport(true,c.signal);setExportOpen(false);setAck(false);await load()}catch(e){setError((e as Error).message||'发版导出失败。')}finally{setBusy(false)}}
 const doRecover=async()=>{if(!recover)return;setBusy(true);try{await api.releaseRecover(recover.version,true,new AbortController().signal);setRecover(null);await load()}catch(e){setError((e as Error).message||'恢复导出失败。')}finally{setBusy(false)}}
 const download=async(a:ReleaseArtifact)=>{try{const value=await api.downloadArtifact(a.id);const url=URL.createObjectURL(value.blob);try{const link=document.createElement('a');link.href=url;link.download=value.filename;link.click()}finally{URL.revokeObjectURL(url)}}catch(e){setError((e as Error).message||'下载失败。')}}
 if(!snapshot&&!error)return <LoadingSkeleton label="正在读取发版日志"/>
 return <><PageHeader eyebrow="RELEASE CONTROL" title="发版日志" description="核对当前会话的 DDL / DML，旋转版本并保留不可变导出。"/>{error&&<InlineError message={error} onRetry={()=>void load()}/>} {snapshot&&<>
 <section className="release-hero"><div><span>SESSION / {snapshot.sessionShortId}</span><strong>{snapshot.currentVersion}</strong><small>DB {snapshot.databaseFingerprint?.slice(0,12)??'UNBOUND'}</small></div><div className="release-count"><span><b>{snapshot.statementCount}</b>可发版</span><span><b>{snapshot.excludedCount}</b>已排除</span><span className={snapshot.failedCount?'danger-text':''}><b>{snapshot.failedCount}</b>失败</span></div><StatusBadge tone={snapshot.bindingState==='MATCH'?'success':snapshot.bindingState==='UNBOUND'?'neutral':'danger'}>{snapshot.bindingState}</StatusBadge><button className="button-primary" disabled={!snapshot.statementCount||snapshot.runningCount>0||busy} onClick={()=>setExportOpen(true)}>发版并导出</button></section>
 {snapshot.runningCount>0&&<div className="activity-warning"><ShieldAlert size={17}/>存在 {snapshot.runningCount} 个运行任务，完成后才能发版。</div>}{snapshot.bindingState==='MISMATCH'&&<div className="activity-warning danger-text">当前默认连接与此版本绑定的数据库不一致。</div>}
 <section className="ops-section"><div className="section-heading"><span>ACTIVE SQL PREVIEW</span><button className="copy-compact" onClick={()=>void navigator.clipboard?.writeText(snapshot.sqlPreview)}><Clipboard size={14}/>复制预览</button></div>{snapshot.sqlPreview?<pre className="release-preview">{snapshot.sqlPreview.split('\n').map((line,i)=><span key={i}><i>{String(i+1).padStart(3,'0')}</i>{line}{'\n'}</span>)}</pre>:<EmptyState title="当前版本暂无 SQL" description="已提交且符合发版用途的 DDL / DML 会记录在此。"/>}{snapshot.previewTruncated&&<p className="truncation-note">预览已按 UTF-8 安全边界截断。</p>}</section>
 <section className="ops-section"><div className="section-heading"><span>STATEMENT LEDGER</span><StatusBadge>{snapshot.entries.length} 条可见</StatusBadge></div><div className="table-scroll"><table className="ops-table"><thead><tr><th>序号</th><th>摘要</th><th>类型</th><th>来源 / 用途</th><th>记录结果</th><th>时间</th></tr></thead><tbody>{snapshot.entries.map((e,i)=><tr key={`${e.sequence}-${e.index}`} className={e.status==='FAILED'?'failed-row':''}><td><code>{e.sequence??`X${i+1}`}</code></td><td>{e.sqlSummary}</td><td>{e.kind}</td><td>{e.source??'未知'} / {e.purpose??'未知'}</td><td>{e.recorded?<StatusBadge tone="success">已记录</StatusBadge>:<StatusBadge tone={e.status==='FAILED'?'danger':'warning'}>{e.exclusionReason||e.status}</StatusBadge>}</td><td>{new Date(e.createdAt).toLocaleString('zh-CN')}</td></tr>)}</tbody></table></div>{snapshot.entriesTruncated&&<p className="truncation-note">条目过多，仅显示安全上限内的记录。</p>}</section>
 <section className="ops-section"><div className="section-heading"><span>IMMUTABLE ARTIFACTS</span><FileClock size={16}/></div>{snapshot.artifacts.length?<div className="artifact-grid">{snapshot.artifacts.map(a=><article key={a.id}><div><StatusBadge tone={a.integrityState==='VERIFIED'?'success':a.integrityState==='RECOVERABLE'?'warning':'danger'}>{a.integrityState}</StatusBadge><code>{a.version}</code></div><h3>{a.filename??'待恢复的密封导出'}</h3><p>{a.statementCount} 条 · {a.byteLength==null?'尺寸待验证':formatBytes(a.byteLength)}</p><code className="sha">{a.sha256??'尚未生成 SHA-256'}</code><div className="row-actions">{a.downloadAvailable&&<button className="button-secondary" aria-label={`下载 ${a.filename}`} onClick={()=>void download(a)}><Download size={15}/>下载</button>}{(a.state==='SEALED'||a.state==='RECOVERY_REQUIRED')&&<button className="button-secondary" onClick={()=>setRecover(a)}><RotateCcw size={15}/>恢复导出</button>}</div></article>)}</div>:<EmptyState title="尚无导出物" description="完成首次发版后，导出物将在此不可变保留。"/>}</section>
 <ConfirmDialog open={exportOpen} title={`发版 ${snapshot.currentVersion}`} confirmLabel={busy?'发版中…':'确认发版'} confirmDisabled={!ack||busy} onClose={()=>{setExportOpen(false);setAck(false)}} onConfirm={()=>void doExport()}><p>将导出 {snapshot.statementCount} 条语句，绑定状态 {snapshot.bindingState}，然后把活动日志旋转到下一版本。</p><label className="acknowledge"><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/>我已了解当前日志将轮转到下一版本</label></ConfirmDialog>
 <ConfirmDialog open={!!recover} title={`恢复 ${recover?.version??''} 导出`} confirmLabel="确认恢复" confirmDisabled={busy} onClose={()=>setRecover(null)} onConfirm={()=>void doRecover()}><p>将从已验证的密封源恢复导出，不会覆盖已完成的导出物。</p></ConfirmDialog></>}</>}
const formatBytes=(n:number)=>n<1024?`${n} B`:`${(n/1024).toFixed(1)} KiB`
